### ISSUE TITLE
Setup Gitter

### ISSUE THREAD

**Issue by javaducky** [coop-code-challenge/cbtf#99]
Having the HipChat room at NISC is nice for us, but inaccessible for the other contributors.  Stumbled upon Gitter in use by SpringBoot and it looked like a nice option.  What do you think?

**Comment by javaducky** [comment]
See this example... https://gitter.im/javaducky/Lobby

**Comment by theismanj** [comment]
Isn't there a way to make a globally accessible Hipchat room? Also, not enough emoticons...

**Comment by javaducky** [comment]
Got one setup now.  Join at https://gitter.im/coop-code-challenge/Lobby
